const db = require('./db');
const { encrypt, hmacHash } = require('./crypto-utils');

async function migrate() {
  // Keep this idempotent: safe to run on every startup.
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS notes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT,
      pinned BOOLEAN NOT NULL DEFAULT FALSE,
      sort_order BIGINT NOT NULL DEFAULT 0,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // Backfill columns for existing DBs
  await db.query(`ALTER TABLE notes ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;`);
  await db.query(`ALTER TABLE notes ADD COLUMN IF NOT EXISTS sort_order BIGINT NOT NULL DEFAULT 0;`);

  await db.query(`
    CREATE TABLE IF NOT EXISTS todos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      text TEXT NOT NULL,
      completed BOOLEAN NOT NULL DEFAULT FALSE,
      category TEXT NOT NULL DEFAULT 'General',
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // Persisted per-user todo categories (beyond the defaults).
  await db.query(`
    CREATE TABLE IF NOT EXISTS todo_categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      normalized_name TEXT NOT NULL,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(user_id, normalized_name)
    );
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS api_keys (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      key TEXT UNIQUE NOT NULL,
      name TEXT,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS recipes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      notes TEXT,
      pdf_filename TEXT,
      pdf_original_name TEXT,
      ingredient_todo_category TEXT,
      ingredient_todos_count INTEGER,
      ingredient_todos_created_at TIMESTAMPTZ,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await db.query('CREATE INDEX IF NOT EXISTS idx_notes_user_id ON notes(user_id)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_notes_user_pinned_sort ON notes(user_id, pinned DESC, sort_order DESC, updated_at DESC)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_todos_user_id ON todos(user_id)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_todo_categories_user_id ON todo_categories(user_id)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON api_keys(user_id)');
  // Backfill columns for existing DBs
  await db.query(`ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredient_todo_category TEXT;`);
  await db.query(`ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredient_todos_count INTEGER;`);
  await db.query(`ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredient_todos_created_at TIMESTAMPTZ;`);

  await db.query('CREATE INDEX IF NOT EXISTS idx_recipes_user_id ON recipes(user_id)');

  // Ingredients table (cached OCR results to avoid expensive API calls)
  await db.query(`
    CREATE TABLE IF NOT EXISTS ingredients (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      quantity TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await db.query('CREATE INDEX IF NOT EXISTS idx_ingredients_recipe_id ON ingredients(recipe_id)');

  // Per-user Anthropic API key (for ingredient extraction)
  await db.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS anthropic_api_key TEXT;`);

  // key_hash column for HMAC-based API key lookup
  await db.query(`ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS key_hash TEXT;`);
  await db.query('CREATE INDEX IF NOT EXISTS idx_api_keys_key_hash ON api_keys(key_hash)');

  // Encrypt existing plaintext API keys and compute HMAC hashes
  const plaintextApiKeys = await db.query(
    `SELECT id, key FROM api_keys WHERE key IS NOT NULL AND key NOT LIKE 'enc:%'`
  );
  for (const row of plaintextApiKeys.rows) {
    await db.query(
      'UPDATE api_keys SET key = $1, key_hash = $2 WHERE id = $3',
      [encrypt(row.key), hmacHash(row.key), row.id]
    );
  }
  // Backfill key_hash for any rows that have encrypted keys but missing hashes (shouldn't happen, but safe)

  // Encrypt existing plaintext Anthropic API keys
  const plaintextAnthropicKeys = await db.query(
    `SELECT id, anthropic_api_key FROM users WHERE anthropic_api_key IS NOT NULL AND anthropic_api_key NOT LIKE 'enc:%'`
  );
  for (const row of plaintextAnthropicKeys.rows) {
    await db.query(
      'UPDATE users SET anthropic_api_key = $1 WHERE id = $2',
      [encrypt(row.anthropic_api_key), row.id]
    );
  }

  if (plaintextApiKeys.rows.length > 0 || plaintextAnthropicKeys.rows.length > 0) {
    console.log(`Encrypted ${plaintextApiKeys.rows.length} API key(s) and ${plaintextAnthropicKeys.rows.length} Anthropic key(s) at rest.`);
  }

  // Helpful indexes
  await db.query('CREATE INDEX IF NOT EXISTS idx_notes_user_updated ON notes(user_id, updated_at DESC)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_todos_user_created ON todos(user_id, created_at DESC)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_recipes_user_updated ON recipes(user_id, updated_at DESC)');
}

module.exports = { migrate };
